<?php

namespace AppBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getFilmsByCategory($category) {

        $qb = $this->createQueryBuilder('f')
            ->where('film.id = film_category.film_id')
            ->andWhere('film_category.category_id = category.id')
            ->andWhere('category.name = category')
            ->setParameter('category', '%' . $category . '%');

        return $qb
            ->getQuery()
            ->getResult();
            }
}
