security:
    encoders:
        AppBundle\Entity\User: bcrypt
    providers:
        user:
            entity:
                class: AppBundle\Entity\User
                property: mail
    firewalls:
        dev:
            pattern: ^(_(profiler|wdr) |css|images|js)/
            security: false
        main:
            provider: user
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                default_target_path: /
            
            logout:
                path: logout
                target: /
    access_control:
        - { path: ^/account, roles: "ROLE_USER"}
        - { path: ^/admin, roles: "ROLE_ADMIN"}